import { DATA_BASE, MANIFEST_URL } from "./paths";
import type { ImageKind } from "./types";

// filename → subfolder, generated by the vite image-manifest plugin from a
// scan of data/images/. Ports GameData.imageFolderIndex: lookups work no
// matter which folder an image was downloaded into.
let manifest: Record<string, string> = {};

export async function loadImageManifest(): Promise<void> {
  const res = await fetch(MANIFEST_URL);
  manifest = await res.json();
}

/**
 * URL of a bundled wiki image; `kind` is only a fallback hint.
 * Ports GameData.imageURL: canonicalize (_ → space, strip File:), look up the
 * folder, then percent-encode — filenames contain spaces and literal HTML
 * entities like &#39;.
 */
export function imageURL(filename: string, kind: ImageKind): string {
  let name = filename.replace(/_/g, " ").trim();
  if (name.startsWith("File:")) name = name.slice(5);
  const folder = manifest[name] ?? kind;
  return `${DATA_BASE}/images/${folder}/${encodeURIComponent(name)}`;
}

/** Whether the image actually exists in the bundle (folder index hit). */
export function imageExists(filename: string): boolean {
  let name = filename.replace(/_/g, " ").trim();
  if (name.startsWith("File:")) name = name.slice(5);
  return name in manifest;
}

export function mapIconURL(icon: string): string {
  return `${DATA_BASE}/map/icons/${encodeURIComponent(icon)}.png`;
}

export function mapTileURLTemplate(): string {
  return `${DATA_BASE}/map/tiles/{z}/{x}/{y}.png`;
}
